import type { Course } from "@/types";

export const SA_COURSES: Course[] = [
  {
    id: "royal-jhb-east",
    name: "Royal Johannesburg & Kensington (East)",
    city: "Johannesburg",
    province: "Gauteng",
    par: 72,
    rating: 74.2,
    slope: 137,
    holes: [
      { hole: 1,  par: 4, si: 7  },
      { hole: 2,  par: 4, si: 1  },
      { hole: 3,  par: 3, si: 15 },
      { hole: 4,  par: 5, si: 9  },
      { hole: 5,  par: 4, si: 3  },
      { hole: 6,  par: 4, si: 11 },
      { hole: 7,  par: 3, si: 17 },
      { hole: 8,  par: 5, si: 5  },
      { hole: 9,  par: 4, si: 13 },
      { hole: 10, par: 4, si: 2  },
      { hole: 11, par: 4, si: 6  },
      { hole: 12, par: 3, si: 18 },
      { hole: 13, par: 5, si: 10 },
      { hole: 14, par: 4, si: 4  },
      { hole: 15, par: 4, si: 8  },
      { hole: 16, par: 3, si: 16 },
      { hole: 17, par: 5, si: 12 },
      { hole: 18, par: 4, si: 14 },
    ],
  },
  {
    id: "glendower",
    name: "Glendower Golf Club",
    city: "Edenvale",
    province: "Gauteng",
    par: 72,
    rating: 73.1,
    slope: 132,
    holes: [
      { hole: 1,  par: 4, si: 9  },
      { hole: 2,  par: 5, si: 3  },
      { hole: 3,  par: 4, si: 13 },
      { hole: 4,  par: 3, si: 17 },
      { hole: 5,  par: 4, si: 1  },
      { hole: 6,  par: 4, si: 7  },
      { hole: 7,  par: 5, si: 11 },
      { hole: 8,  par: 3, si: 15 },
      { hole: 9,  par: 4, si: 5  },
      { hole: 10, par: 4, si: 6  },
      { hole: 11, par: 4, si: 2  },
      { hole: 12, par: 3, si: 16 },
      { hole: 13, par: 5, si: 10 },
      { hole: 14, par: 4, si: 4  },
      { hole: 15, par: 4, si: 8  },
      { hole: 16, par: 3, si: 18 },
      { hole: 17, par: 5, si: 14 },
      { hole: 18, par: 4, si: 12 },
    ],
  },
  {
    id: "randpark-bushwillow",
    name: "Randpark Golf Club (Bushwillow)",
    city: "Randburg",
    province: "Gauteng",
    par: 72,
    rating: 72.5,
    slope: 129,
    holes: [
      { hole: 1,  par: 4, si: 11 },
      { hole: 2,  par: 3, si: 15 },
      { hole: 3,  par: 5, si: 5  },
      { hole: 4,  par: 4, si: 1  },
      { hole: 5,  par: 4, si: 9  },
      { hole: 6,  par: 4, si: 7  },
      { hole: 7,  par: 3, si: 17 },
      { hole: 8,  par: 5, si: 3  },
      { hole: 9,  par: 4, si: 13 },
      { hole: 10, par: 4, si: 2  },
      { hole: 11, par: 5, si: 6  },
      { hole: 12, par: 4, si: 10 },
      { hole: 13, par: 3, si: 18 },
      { hole: 14, par: 4, si: 4  },
      { hole: 15, par: 5, si: 8  },
      { hole: 16, par: 4, si: 12 },
      { hole: 17, par: 3, si: 16 },
      { hole: 18, par: 4, si: 14 },
    ],
  },
  {
    id: "wanderers",
    name: "Wanderers Golf Club",
    city: "Johannesburg",
    province: "Gauteng",
    par: 72,
    rating: 73.8,
    slope: 134,
    holes: [
      { hole: 1,  par: 4, si: 5  },
      { hole: 2,  par: 5, si: 1  },
      { hole: 3,  par: 4, si: 11 },
      { hole: 4,  par: 3, si: 17 },
      { hole: 5,  par: 4, si: 7  },
      { hole: 6,  par: 4, si: 3  },
      { hole: 7,  par: 5, si: 9  },
      { hole: 8,  par: 3, si: 15 },
      { hole: 9,  par: 4, si: 13 },
      { hole: 10, par: 4, si: 4  },
      { hole: 11, par: 4, si: 8  },
      { hole: 12, par: 3, si: 16 },
      { hole: 13, par: 5, si: 2  },
      { hole: 14, par: 4, si: 10 },
      { hole: 15, par: 4, si: 6  },
      { hole: 16, par: 3, si: 18 },
      { hole: 17, par: 5, si: 12 },
      { hole: 18, par: 4, si: 14 },
    ],
  },
  {
    id: "centurion-cc",
    name: "Centurion Country Club",
    city: "Centurion",
    province: "Gauteng",
    par: 72,
    rating: 72.0,
    slope: 128,
    holes: [
      { hole: 1,  par: 4, si: 8  },
      { hole: 2,  par: 5, si: 4  },
      { hole: 3,  par: 4, si: 12 },
      { hole: 4,  par: 3, si: 16 },
      { hole: 5,  par: 4, si: 2  },
      { hole: 6,  par: 4, si: 6  },
      { hole: 7,  par: 5, si: 10 },
      { hole: 8,  par: 3, si: 18 },
      { hole: 9,  par: 4, si: 14 },
      { hole: 10, par: 4, si: 1  },
      { hole: 11, par: 4, si: 5  },
      { hole: 12, par: 3, si: 17 },
      { hole: 13, par: 5, si: 9  },
      { hole: 14, par: 4, si: 3  },
      { hole: 15, par: 4, si: 7  },
      { hole: 16, par: 3, si: 15 },
      { hole: 17, par: 5, si: 11 },
      { hole: 18, par: 4, si: 13 },
    ],
  },
  {
    id: "serengeti",
    name: "Serengeti Golf & Wildlife Estate",
    city: "Kempton Park",
    province: "Gauteng",
    par: 72,
    rating: 74.5,
    slope: 139,
    holes: [
      { hole: 1,  par: 4, si: 10 },
      { hole: 2,  par: 4, si: 2  },
      { hole: 3,  par: 5, si: 6  },
      { hole: 4,  par: 3, si: 14 },
      { hole: 5,  par: 4, si: 4  },
      { hole: 6,  par: 4, si: 8  },
      { hole: 7,  par: 3, si: 18 },
      { hole: 8,  par: 5, si: 12 },
      { hole: 9,  par: 4, si: 16 },
      { hole: 10, par: 4, si: 1  },
      { hole: 11, par: 4, si: 7  },
      { hole: 12, par: 3, si: 15 },
      { hole: 13, par: 5, si: 5  },
      { hole: 14, par: 4, si: 3  },
      { hole: 15, par: 4, si: 9  },
      { hole: 16, par: 3, si: 17 },
      { hole: 17, par: 5, si: 11 },
      { hole: 18, par: 4, si: 13 },
    ],
  },
  {
    id: "durban-cc",
    name: "Durban Country Club",
    city: "Durban",
    province: "KwaZulu-Natal",
    par: 72,
    rating: 74.8,
    slope: 140,
    holes: [
      { hole: 1,  par: 4, si: 3  },
      { hole: 2,  par: 4, si: 9  },
      { hole: 3,  par: 5, si: 1  },
      { hole: 4,  par: 3, si: 13 },
      { hole: 5,  par: 4, si: 7  },
      { hole: 6,  par: 4, si: 5  },
      { hole: 7,  par: 3, si: 17 },
      { hole: 8,  par: 5, si: 11 },
      { hole: 9,  par: 4, si: 15 },
      { hole: 10, par: 4, si: 2  },
      { hole: 11, par: 5, si: 4  },
      { hole: 12, par: 4, si: 8  },
      { hole: 13, par: 3, si: 18 },
      { hole: 14, par: 4, si: 6  },
      { hole: 15, par: 5, si: 10 },
      { hole: 16, par: 4, si: 12 },
      { hole: 17, par: 3, si: 16 },
      { hole: 18, par: 4, si: 14 },
    ],
  },
  {
    id: "zimbali",
    name: "Zimbali Country Club",
    city: "Ballito",
    province: "KwaZulu-Natal",
    par: 72,
    rating: 73.6,
    slope: 135,
    holes: [
      { hole: 1,  par: 5, si: 5  },
      { hole: 2,  par: 4, si: 1  },
      { hole: 3,  par: 4, si: 9  },
      { hole: 4,  par: 3, si: 15 },
      { hole: 5,  par: 4, si: 3  },
      { hole: 6,  par: 4, si: 11 },
      { hole: 7,  par: 5, si: 7  },
      { hole: 8,  par: 3, si: 17 },
      { hole: 9,  par: 4, si: 13 },
      { hole: 10, par: 4, si: 4  },
      { hole: 11, par: 4, si: 2  },
      { hole: 12, par: 3, si: 16 },
      { hole: 13, par: 5, si: 6  },
      { hole: 14, par: 4, si: 8  },
      { hole: 15, par: 4, si: 10 },
      { hole: 16, par: 3, si: 18 },
      { hole: 17, par: 5, si: 12 },
      { hole: 18, par: 4, si: 14 },
    ],
  },
  {
    id: "gary-player-sun-city",
    name: "Sun City \u2013 Gary Player Country Club",
    city: "Sun City",
    province: "North West",
    par: 72,
    rating: 76.1,
    slope: 144,
    holes: [
      { hole: 1,  par: 4, si: 4  },
      { hole: 2,  par: 5, si: 2  },
      { hole: 3,  par: 4, si: 10 },
      { hole: 4,  par: 3, si: 16 },
      { hole: 5,  par: 4, si: 6  },
      { hole: 6,  par: 4, si: 8  },
      { hole: 7,  par: 5, si: 12 },
      { hole: 8,  par: 3, si: 18 },
      { hole: 9,  par: 4, si: 14 },
      { hole: 10, par: 4, si: 1  },
      { hole: 11, par: 4, si: 5  },
      { hole: 12, par: 3, si: 17 },
      { hole: 13, par: 5, si: 9  },
      { hole: 14, par: 4, si: 3  },
      { hole: 15, par: 4, si: 7  },
      { hole: 16, par: 3, si: 15 },
      { hole: 17, par: 5, si: 11 },
      { hole: 18, par: 4, si: 13 },
    ],
  },
  {
    id: "fancourt-montagu",
    name: "Fancourt (Montagu)",
    city: "George",
    province: "Western Cape",
    par: 72,
    rating: 75.3,
    slope: 141,
    holes: [
      { hole: 1,  par: 4, si: 6  },
      { hole: 2,  par: 4, si: 2  },
      { hole: 3,  par: 5, si: 8  },
      { hole: 4,  par: 3, si: 14 },
      { hole: 5,  par: 4, si: 4  },
      { hole: 6,  par: 4, si: 10 },
      { hole: 7,  par: 3, si: 18 },
      { hole: 8,  par: 5, si: 12 },
      { hole: 9,  par: 4, si: 16 },
      { hole: 10, par: 4, si: 1  },
      { hole: 11, par: 4, si: 7  },
      { hole: 12, par: 3, si: 15 },
      { hole: 13, par: 5, si: 5  },
      { hole: 14, par: 4, si: 3  },
      { hole: 15, par: 4, si: 9  },
      { hole: 16, par: 3, si: 17 },
      { hole: 17, par: 5, si: 11 },
      { hole: 18, par: 4, si: 13 },
    ],
  },
  {
    id: "pearl-valley",
    name: "Pearl Valley Golf Estates",
    city: "Paarl",
    province: "Western Cape",
    par: 72,
    rating: 73.9,
    slope: 136,
    holes: [
      { hole: 1,  par: 4, si: 7  },
      { hole: 2,  par: 5, si: 3  },
      { hole: 3,  par: 4, si: 11 },
      { hole: 4,  par: 3, si: 15 },
      { hole: 5,  par: 4, si: 1  },
      { hole: 6,  par: 4, si: 9  },
      { hole: 7,  par: 5, si: 5  },
      { hole: 8,  par: 3, si: 17 },
      { hole: 9,  par: 4, si: 13 },
      { hole: 10, par: 4, si: 4  },
      { hole: 11, par: 4, si: 2  },
      { hole: 12, par: 3, si: 16 },
      { hole: 13, par: 5, si: 6  },
      { hole: 14, par: 4, si: 8  },
      { hole: 15, par: 4, si: 10 },
      { hole: 16, par: 3, si: 18 },
      { hole: 17, par: 5, si: 12 },
      { hole: 18, par: 4, si: 14 },
    ],
  },
  {
    id: "westlake",
    name: "Westlake Golf Club",
    city: "Cape Town",
    province: "Western Cape",
    par: 72,
    rating: 71.8,
    slope: 127,
    holes: [
      { hole: 1,  par: 4, si: 9  },
      { hole: 2,  par: 4, si: 3  },
      { hole: 3,  par: 3, si: 13 },
      { hole: 4,  par: 5, si: 1  },
      { hole: 5,  par: 4, si: 7  },
      { hole: 6,  par: 4, si: 5  },
      { hole: 7,  par: 3, si: 17 },
      { hole: 8,  par: 5, si: 11 },
      { hole: 9,  par: 4, si: 15 },
      { hole: 10, par: 4, si: 2  },
      { hole: 11, par: 5, si: 4  },
      { hole: 12, par: 4, si: 10 },
      { hole: 13, par: 3, si: 18 },
      { hole: 14, par: 4, si: 6  },
      { hole: 15, par: 5, si: 8  },
      { hole: 16, par: 4, si: 12 },
      { hole: 17, par: 3, si: 16 },
      { hole: 18, par: 4, si: 14 },
    ],
  },
  {
    id: "leopard-creek",
    name: "Leopard Creek Country Club",
    city: "Malelane",
    province: "Mpumalanga",
    par: 72,
    rating: 75.8,
    slope: 142,
    holes: [
      { hole: 1,  par: 4, si: 5  },
      { hole: 2,  par: 4, si: 1  },
      { hole: 3,  par: 5, si: 7  },
      { hole: 4,  par: 3, si: 15 },
      { hole: 5,  par: 4, si: 3  },
      { hole: 6,  par: 4, si: 11 },
      { hole: 7,  par: 5, si: 9  },
      { hole: 8,  par: 3, si: 17 },
      { hole: 9,  par: 4, si: 13 },
      { hole: 10, par: 4, si: 2  },
      { hole: 11, par: 4, si: 6  },
      { hole: 12, par: 3, si: 18 },
      { hole: 13, par: 5, si: 4  },
      { hole: 14, par: 4, si: 8  },
      { hole: 15, par: 4, si: 10 },
      { hole: 16, par: 3, si: 16 },
      { hole: 17, par: 5, si: 12 },
      { hole: 18, par: 4, si: 14 },
    ],
  },
  {
    id: "humewood",
    name: "Humewood Golf Club",
    city: "Port Elizabeth",
    province: "Eastern Cape",
    par: 72,
    rating: 73.4,
    slope: 133,
    holes: [
      { hole: 1,  par: 4, si: 8  },
      { hole: 2,  par: 5, si: 4  },
      { hole: 3,  par: 4, si: 12 },
      { hole: 4,  par: 3, si: 16 },
      { hole: 5,  par: 4, si: 2  },
      { hole: 6,  par: 4, si: 6  },
      { hole: 7,  par: 5, si: 10 },
      { hole: 8,  par: 3, si: 18 },
      { hole: 9,  par: 4, si: 14 },
      { hole: 10, par: 4, si: 1  },
      { hole: 11, par: 4, si: 7  },
      { hole: 12, par: 3, si: 15 },
      { hole: 13, par: 5, si: 5  },
      { hole: 14, par: 4, si: 3  },
      { hole: 15, par: 4, si: 9  },
      { hole: 16, par: 3, si: 17 },
      { hole: 17, par: 5, si: 11 },
      { hole: 18, par: 4, si: 13 },
    ],
  },
  {
    id: "selborne",
    name: "Selborne Golf Estate",
    city: "Pennington",
    province: "KwaZulu-Natal",
    par: 72,
    rating: 72.8,
    slope: 130,
    holes: [
      { hole: 1,  par: 4, si: 6  },
      { hole: 2,  par: 4, si: 2  },
      { hole: 3,  par: 5, si: 8  },
      { hole: 4,  par: 3, si: 14 },
      { hole: 5,  par: 4, si: 4  },
      { hole: 6,  par: 4, si: 10 },
      { hole: 7,  par: 3, si: 18 },
      { hole: 8,  par: 5, si: 12 },
      { hole: 9,  par: 4, si: 16 },
      { hole: 10, par: 4, si: 1  },
      { hole: 11, par: 4, si: 7  },
      { hole: 12, par: 3, si: 15 },
      { hole: 13, par: 5, si: 3  },
      { hole: 14, par: 4, si: 9  },
      { hole: 15, par: 4, si: 5  },
      { hole: 16, par: 3, si: 17 },
      { hole: 17, par: 5, si: 11 },
      { hole: 18, par: 4, si: 13 },
    ],
  },
];

export const PROVINCES: string[] = [
  ...new Set(SA_COURSES.map((c) => c.province)),
].sort();

export function getCourseById(id: string): Course | null {
  return SA_COURSES.find((c) => c.id === id) ?? null;
}

export function getCoursesByProvince(province: string): Course[] {
  return SA_COURSES.filter((c) => c.province === province);
}

export function searchCourses(query: string): Course[] {
  const q = query.toLowerCase();
  return SA_COURSES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.city.toLowerCase().includes(q) ||
      c.province.toLowerCase().includes(q)
  );
}
